### ISSUE TITLE
Log4j vulnerability

### ISSUE THREAD

**Issue by nikosnikolaidis** [kiegroup/kie-soup#249]
I am extending the functionality of Kie Workbench and I found out that it uses the dependency `org.kie.soup:kie-soup-dataset-elasticsearch` from inside `org.dashbuilder:dashbuilder-dataset-cdi`.
The `org.kie.soup:kie-soup-dataset-elasticsearch` uses the 5.6.16 version of `org.elasticsearch.client:transport` that has the Major vulnerabilities of Log4j.
If you update the dependency `org.elasticsearch.client:transport` to version 7.17.1 the problem should be fixed.
There is a similar version for the `org.elasticsearch:elasticsearch`, so I guess you can just change the property value of `version.org.elasticsearch` to 7.17.1 of the pox.xml.

**Comment by mareknovotny** [comment]
elasticsearch is basically there only to enable integration with ElasticSearch itself.
We are removing this integration anyway is a legacy component
